import type { Metadata } from "next";
import { Geist, Geist_Mono, Libre_Franklin, Noto_Sans, Pixelify_Sans, Signika } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

/** The pixelated font used before. Leaving it here as reference, because it was hard to find. */
// export const pixelatedSans = Pixelify_Sans({
// 	variable: "--font-pixelated-sans",
// 	subsets: ["latin"],
// 	weight: ["400", "700"],
// });

export const libreFranklin = Libre_Franklin({
	variable: "--font-libre-franklin",
	subsets: ["latin"],
	weight: ["400", "700"],
	style: ["normal", "italic"],
});

export const signika = Signika({
	variable: "--font-signika",
	subsets: ["latin"],
	weight: ["400", "700"],
	style: ["normal"],
});

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}>{children}</body>
		</html>
	);
}
